name: Format python code
on: push
jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get PR Data
        uses: actions/github-script@v6
        id: get_issue_number
        with:
          script: |
            if (context.issue.number) {
              // Return issue number if present
              return context.issue.number;
            } else {
              // Otherwise return issue number from commit
              return (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0].number;
            }
          result-encoding: string
      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v2
        with:
          args: --exit-code --max-line-length 120 --recursive --in-place --aggressive --aggressive .
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{steps.get_issue_number.outputs.result}}
          comment-author: "github-actions[bot]"
      - name: Create comment if autopep8 made NO changes
        if: ${{ steps.fc.outputs.comment-id == '' && steps.autopep8.outputs.exit-code != 2}}
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{steps.get_issue_number.outputs.result}}
          body: |
            Code has no PEP8 errors!
          reactions: hooray
      - name: Create comment if autopep8 made changes
        if: ${{ steps.fc.outputs.comment-id == '' && steps.autopep8.outputs.exit-code == 2}}
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{steps.get_issue_number.outputs.result}}
          body: |
            Code in this pull request contains PEP8 errors, please write the command `/autopep8` in the comments below to create another pull request with automatic fixes.
          reactions: confused
      - name: Update comment if NOT fixed
        if: ${{ steps.fc.outputs.comment-id != '' && steps.autopep8.outputs.exit-code == 2}}
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: |
            Code in this pull request **still** contains PEP8 errors, please write the command `/autopep8` in the comments below to create another pull request with automatic fixes.

            ##### Comment last updated at ${{ github.event.repository.updated_at}}
          reactions: eyes
      - name: Update comment if fixed
        if: ${{ steps.fc.outputs.comment-id != '' && steps.autopep8.outputs.exit-code != 2}}
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: |
            All PEP8 errors has been fixed, thanks <3

            ##### Comment last updated at ${{ github.event.repository.updated_at}}
          reactions: hooray
      - name: Fail if autopep8 made changes
        if: steps.autopep8.outputs.exit-code == 2
        run: exit 1
