name: Slash Command Dispatch
on:
  issue_comment:
    # Type "edited" added here for test purposes. Where possible, avoid
    # using to prevent processing unnecessary events.
    types: [created, edited]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      # Basic configuration
      - name: Slash Command Dispatch
        uses: ./
        with:
          token: ${{ secrets.PAT }}
          commands: |
            hello-world-local
          permission: none
          issue-type: issue
